version: "3.7"

services:
  api:
    build: .
    environment:
      - APP_SETTINGS=production
      - FILE_EXTENSION=.jpg
    ports:
      - 5000:5000
    command: "gunicorn -b 0.0.0.0:5000 wsgi:app --reload"
    volumes:
      - ./:/app
    stdin_open: true
    tty: true
